import { Router } from 'express';
import authRoutes from '../modules/auth/auth.routes.js';
import userRoutes from '../modules/users/user.routes.js';
import profileRoutes from '../modules/profiles/profile.routes.js';
import householdRoutes from '../modules/household/household.routes.js';
import wardrobeRoutes from '../modules/wardrobe/wardrobe.routes.js';
import collectionRoutes from '../modules/collections/collection.routes.js';
import typeRoutes from '../modules/types/type.routes.js';
import itemRoutes from '../modules/items/item.routes.js';
import laundryRoutes from '../modules/laundry/laundry.routes.js';
import plannerRoutes from '../modules/planner/planner.routes.js';
import outfitRoutes from '../modules/outfits/outfit.routes.js';
import aiRoutes from '../modules/ai/ai.routes.js';
import subscriptionRoutes from '../modules/subscriptions/subscription.routes.js';
import planRoutes from '../modules/plans/plan.routes.js';
import notificationRoutes from '../modules/notifications/notification.routes.js';
import paymentRoutes from '../modules/payments/payment.routes.js';

const router = Router();
router.get('/health', (req,res)=>res.json({success:true,message:'SmartWardrobe API is running',timestamp:new Date().toISOString()}));
router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/profile', profileRoutes);
router.use('/household', householdRoutes);
router.use('/wardrobe', wardrobeRoutes);
router.use('/collections', collectionRoutes);
router.use('/types', typeRoutes);
router.use('/items', itemRoutes);
router.use('/laundry', laundryRoutes);
router.use('/planner', plannerRoutes);
router.use('/outfits', outfitRoutes);
router.use('/ai', aiRoutes);
router.use('/subscriptions', subscriptionRoutes);
router.use('/plans', planRoutes);
router.use('/notifications', notificationRoutes);
router.use('/payments', paymentRoutes);
export default router;
