import {Router} from 'express';
import * as c from './payment.controller.js';
import {requireAuth} from '../../middleware/auth.middleware.js';
import {allowRoles} from '../../middleware/role.middleware.js';
import {ROLES} from '../../constants/roles.js';
import {upload} from '../../middleware/upload.middleware.js';
import {asyncHandler} from '../../utils/asyncHandler.js';
const r=Router();r.use(requireAuth);
r.get('/methods',asyncHandler(c.methods));
r.get('/config',asyncHandler(c.config));
r.get('/checkout/:planCode',asyncHandler(c.checkout));
r.post('/submit',upload.single('proof'),asyncHandler(c.submit));
r.get('/mine',asyncHandler(c.mine));
r.get('/admin/pending',allowRoles(ROLES.SUPER_ADMIN),asyncHandler(c.pending));
r.get('/admin/methods',allowRoles(ROLES.SUPER_ADMIN),asyncHandler(c.adminMethods));
r.post('/admin/methods',allowRoles(ROLES.SUPER_ADMIN),upload.single('qrImage'),asyncHandler(c.createMethod));
r.patch('/admin/methods/:id',allowRoles(ROLES.SUPER_ADMIN),upload.single('qrImage'),asyncHandler(c.updateMethod));
r.delete('/admin/methods/:id',allowRoles(ROLES.SUPER_ADMIN),asyncHandler(c.removeMethod));
r.patch('/admin/config',allowRoles(ROLES.SUPER_ADMIN),upload.single('qrImage'),asyncHandler(c.updateConfig));
r.patch('/admin/:id/review',allowRoles(ROLES.SUPER_ADMIN),asyncHandler(c.review));
export default r;
